sonar.projectKey=hasadna_knesset-data-pipelines
sonar.organization=hasadna
sonar.projectName=knesset-data-pipelines

sonar.sources=airflow/knesset_data_pipelines
sonar.tests=airflow/knesset_data_pipelines
sonar.test.inclusions=**/test_*.py,**/*_test.py
sonar.exclusions=**/node_modules/**,datapackage_pipelines_knesset/**

sonar.python.version=3.8
sonar.sourceEncoding=UTF-8
