{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name | default "flower"}}
spec:
  selector:
    app: {{.Values.name | default "flower"}}
  ports:
  - port: 5555
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{.Values.name | default "flower"}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{.Values.name | default "flower"}}
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.global.gkeNodePool | default "default-pool" | quote }}
      containers:
      - name: flower
        image: {{.Values.image | default "orihoch/knesset-data-pipelines:latest" | quote}}
        args: ["flower"]
        env:
        - name: DPP_REDIS_HOST
          value: "redis"
        - name: FLOWER_PORT
          value: "5555"
        {{ if .Values.urlPrefix }}
        - name: FLOWER_URL_PREFIX
          value: {{.Values.urlPrefix | quote}}
        {{ end }}
        command: ['/knesset/bin/celery_run.sh', 'flower']
        ports: [{containerPort: 5555}]
        resources:
          requests:
            cpu: {{.Values.cpuRequests | default "0.001"}}
            memory: {{.Values.memoryRequests | default "50Mi" | quote}}
#        readinessProbe:
#          initialDelaySeconds: 5
#          periodSeconds: 10
#          timeoutSeconds: 10
#          httpGet:
#            path: /
#            port: 5555
{{ end }}
