[project]
name = "knesset-data-pipelines"
version = "0.1.0"
requires-python = "==3.8.*"
dependencies = [
    "SQLAlchemy==1.4.46",
    "click==8.1.3",
    "ruamel.yaml==0.17.21",
    "python-dotenv==0.21.1",
    "dataflows==0.3.16",
    "requests[socks]==2.28.2",
    "beautifulsoup4==4.11.2",
    "google-cloud-storage==2.7.0",
    "google-api-python-client==2.90.0",
    "apache-airflow-providers-cncf-kubernetes==7.2.0",
    "pyquery==1.4.0",
]

#[dependency-groups]
#dev = [
#    "pytest>=8.3.5",
#]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
knesset-data-pipelines = "knesset_data_pipelines.cli:main"
